# Uncomment the next line to define a global platform for your project
ENV['SWIFT_VERSION'] = '5'
platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Unity-iPhone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Particle Network Base
  pod 'ParticleNetworkBase', '2.0.3'
  pod 'ParticleNetworkChains', '2.0.3'
  
  # Particle Connect Service
  pod 'ConnectCommon', '2.0.3'
  pod 'ConnectEVMAdapter', '2.0.3'
  pod 'ConnectSolanaAdapter', '2.0.3'
  pod 'ConnectWalletConnectAdapter', '2.0.3'
  pod 'ConnectPhantomAdapter', '2.0.3'
  pod 'ParticleConnect', '2.0.3'

  # Particle Wallet Service
  pod 'ParticleWalletConnect', '2.0.3'
  pod 'ParticleWalletAPI', '2.0.3'
  pod 'ParticleWalletGUI', '2.0.3'
  
  # Particle AA
  pod 'ParticleAA', '2.0.3'
  
  # Particle Auth Core
  pod 'AuthCoreAdapter', '2.0.3'
  pod 'ParticleAuthCore', '2.0.3'
  pod 'ParticleMPCCore', '2.0.3'
  pod 'Thresh', '2.0.3'
  
  pod 'ParticleConnectKit', '2.0.3'
  
  pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
  pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
  pod 'WalletConnectSwiftV2', :git => 'https://github.com/SunZhiC/WalletConnectSwiftV2.git', :branch => 'particle'
  
  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'UnityFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnityFramework

end


post_install do |installer|
  
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "x86_64"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
         end
    end
  end
  
  # This is necessary for Xcode 14, because it signs resource bundles by default
  # when building for devices.
  installer.target_installation_results.pod_target_installation_results
  .each do |pod_name, target_installation_result|
    target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
      resource_bundle_target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
end
